# Generated by Django 4.0.4 on 2022-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='file',
            new_name='file_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='hit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
