# Generated by Django 4.0.4 on 2022-05-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'progress_statuses',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('start_recruit', models.DateField()),
                ('end_recruit', models.DateField()),
                ('start_project', models.DateField()),
                ('end_project', models.DateField()),
                ('description', models.TextField()),
                ('like', models.PositiveBigIntegerField()),
                ('hit', models.PositiveBigIntegerField()),
                ('front_vacancy', models.PositiveSmallIntegerField()),
                ('back_vacancy', models.PositiveSmallIntegerField()),
                ('is_online', models.BooleanField(default=True)),
                ('progress_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.progressstatus')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'project_categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.technologystack')),
            ],
            options={
                'db_table': 'projects_stacks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.region'),
        ),
    ]
