# Generated by Django 4.0.4 on 2022-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategory',
            old_name='category',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='back_vacancy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='front_vacancy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='hit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
