# Generated by Django 4.0.4 on 2022-05-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologystack',
            name='project',
            field=models.ManyToManyField(through='projects.ProjectStack', to='projects.project'),
        ),
        migrations.AddField(
            model_name='technologystack',
            name='stack_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.stackcategory'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.imagetype'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='image',
            name='technology_stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.technologystack'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
