# Generated by Django 4.0.4 on 2022-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
