# Generated by Django 4.0.4 on 2022-05-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applies', '0001_initial'),
        ('projects', '0001_initial'),
        ('commons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplystack',
            name='technology_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.technologystack'),
        ),
        migrations.AddField(
            model_name='projectapply',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.position'),
        ),
        migrations.AddField(
            model_name='projectapply',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectapply',
            name='project_apply_stack',
            field=models.ManyToManyField(through='applies.ProjectApplyStack', to='commons.technologystack'),
        ),
        migrations.AddField(
            model_name='projectapply',
            name='project_apply_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applies.projectapplystate'),
        ),
        migrations.AddField(
            model_name='projectapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
