# Generated by Django 4.0.4 on 2022-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectApplyState',
            new_name='ProjectApplyStatus',
        ),
        migrations.AlterModelTable(
            name='projectapplystatus',
            table='projects_applies_status',
        ),
    ]
