# Generated by Django 4.0.4 on 2022-05-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0004_rename_status_projectapplystatus_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectapply',
            old_name='project_apply_state',
            new_name='project_apply_status',
        ),
        migrations.RemoveField(
            model_name='projectapplystatus',
            name='request_status',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='project_apply_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applies.projectapplystatus'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='projectapplystatus',
            table='projects_applies_statuses',
        ),
    ]
